### ISSUE TITLE
Bug? Shows error when right click

### ISSUE THREAD

**Issue by Mollfunn** [Angry362/Lifestyle-Mod-Project-Zomboid-#16]
```
LOG  : General     , 1703785969605> -----------------------------------------
STACK TRACE
-----------------------------------------
function: Add -- file: AdminTestCM.lua line # 45 | MOD: Lifestyle
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@55970377
function: createMenu -- file: ISWorldObjectContextMenu.lua line # 1543 | Vanilla
function: createMenu -- file: ISMenuContextWorld.lua line # 50 | Vanilla
function: createWorldMenu -- file: ISContextManager.lua line # 28 | Vanilla
function: doRClick -- file: ISObjectClickHandler.lua line # 60 | Vanilla
function: onObjectRightMouseButtonUp -- file: ISObjectClickHandler.lua line # 379 | Vanilla

ERROR: General     , 1703785969605> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: Expressions of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1703785969605> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: Expressions of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:214)
	at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:228)
	at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:3086)
	at jdk.internal.reflect.GeneratedMethodAccessor520.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:79)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
	at zombie.ui.UIManager.update(UIManager.java:938)
	at zombie.GameWindow.logic(GameWindow.java:262)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:667)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1703785969607> -----------------------------------------
STACK TRACE
-----------------------------------------
function: Add -- file: AdminTestCM.lua line # 45 | MOD: Lifestyle
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@55970377
function: createMenu -- file: ISWorldObjectContextMenu.lua line # 1543 | Vanilla
function: createMenu -- file: ISMenuContextWorld.lua line # 50 | Vanilla
function: createWorldMenu -- file: ISContextManager.lua line # 28 | Vanilla
function: doRClick -- file: ISObjectClickHandler.lua line # 60 | Vanilla
function: onObjectRightMouseButtonUp -- file: ISObjectClickHandler.lua line # 379 | Vanilla

LOG  : General     , 1703785970455> -------------------------------------------------------------
attempted index: Expressions of non-table: null

LOG  : General     , 1703785970456> -----------------------------------------
STACK TRACE
-----------------------------------------
function: Add -- file: AdminTestCM.lua line # 45 | MOD: Lifestyle
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@55970377
function: createMenu -- file: ISWorldObjectContextMenu.lua line # 1543 | Vanilla
function: createMenu -- file: ISMenuContextWorld.lua line # 50 | Vanilla
function: createWorldMenu -- file: ISContextManager.lua line # 28 | Vanilla
function: doRClick -- file: ISObjectClickHandler.lua line # 60 | Vanilla
function: onObjectRightMouseButtonUp -- file: ISObjectClickHandler.lua line # 379 | Vanilla

ERROR: General     , 1703785970456> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: Expressions of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1703785970456> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: Expressions of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:214)
	at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:228)
	at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:3086)
	at jdk.internal.reflect.GeneratedMethodAccessor520.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:79)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
	at zombie.ui.UIManager.update(UIManager.java:938)
	at zombie.GameWindow.logic(GameWindow.java:262)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:667)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1703785970457> -----------------------------------------
STACK TRACE
-----------------------------------------
function: Add -- file: AdminTestCM.lua line # 45 | MOD: Lifestyle
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@55970377
function: createMenu -- file: ISWorldObjectContextMenu.lua line # 1543 | Vanilla
function: createMenu -- file: ISMenuContextWorld.lua line # 50 | Vanilla
function: createWorldMenu -- file: ISContextManager.lua line # 28 | Vanilla
function: doRClick -- file: ISObjectClickHandler.lua line # 60 | Vanilla
function: onObjectRightMouseButtonUp -- file: ISObjectClickHandler.lua line # 379 | Vanilla

LOG  : General     , 1703785970960> -------------------------------------------------------------
attempted index: Expressions of non-table: null

LOG  : General     , 1703785970960> -----------------------------------------
STACK TRACE
-----------------------------------------
function: Add -- file: AdminTestCM.lua line # 45 | MOD: Lifestyle
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@55970377
function: createMenu -- file: ISWorldObjectContextMenu.lua line # 1543 | Vanilla
function: createMenu -- file: ISMenuContextWorld.lua line # 50 | Vanilla
function: createWorldMenu -- file: ISContextManager.lua line # 28 | Vanilla
function: doRClick -- file: ISObjectClickHandler.lua line # 60 | Vanilla
function: onObjectRightMouseButtonUp -- file: ISObjectClickHandler.lua line # 379 | Vanilla

ERROR: General     , 1703785970960> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: Expressions of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1703785970961> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: Expressions of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:214)
	at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:228)
	at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:3086)
	at jdk.internal.reflect.GeneratedMethodAccessor520.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:79)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
	at zombie.ui.UIManager.update(UIManager.java:938)
	at zombie.GameWindow.logic(GameWindow.java:262)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:667)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1703785970962> -----------------------------------------
STACK TRACE
-----------------------------------------
function: Add -- file: AdminTestCM.lua line # 45 | MOD: Lifestyle
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@55970377
function: createMenu -- file: ISWorldObjectContextMenu.lua line # 1543 | Vanilla
function: createMenu -- file: ISMenuContextWorld.lua line # 50 | Vanilla
function: createWorldMenu -- file: ISContextManager.lua line # 28 | Vanilla
function: doRClick -- file: ISObjectClickHandler.lua line # 60 | Vanilla
function: onObjectRightMouseButtonUp -- file: ISObjectClickHandler.lua line # 379 | Vanilla

```

**Comment by Angry362** [comment]
Hi Mollfunn! This happens because the game can't find the sandbox value, thus returning an error. This is most likely due to having downloaded a previous version of lifestyle that didn't have sandbox options (either a reupload or a modpack) conflicting with the newer version. You need to unsubscribe from the reupload or clean your mods if you can't find it.
