### ISSUE TITLE
I keep getting an error related to something called homesick?

### ISSUE THREAD

**Issue by Tengutome** [Angry362/Lifestyle-Mod-Project-Zomboid-#17]
`attempted index: HomeSick of non-table: null
function: LSEveryTenMinutes -- file: LSCreation.lua line # 112 | MOD: Lifestyle
java.lang.RuntimeException: attempted index: HomeSick of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:65)
    at zombie.GameTime.update(GameTime.java:671)
    at zombie.gameStates.IngameState.UpdateStuff(IngameState.java:566)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1623)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

I cant seem to figure out how to fix it without uninstalling the entire mod but I really like it.

**Comment by Angry362** [comment]
Hey Tengutome, this is an old bug that was fixed in a recent patch. Make sure you don't have another version of lifestyle installed like a reupload or modpack, these will mess up with the original version even if you don't enable them.

**Comment by Angry362** [comment]
Considering more than a week passed without further response I'll presume my previous guess was correct and the issue was resolved. Please let me know should you need help in the future :)
