### ISSUE TITLE
Error keeps popping up

### ISSUE THREAD

**Issue by XxMilkChocolate** [Angry362/Lifestyle-Mod-Project-Zomboid-#19]
Hello i'm running you mod with quite a few others and this error keeps popping up when i get into the game

`attempted index: destroy of non-table: null
function: LSMenuOnDestroy -- file: MenuOverlay.lua line # 398 | MOD: Lifestyle
java.lang.RuntimeException: attempted index: destroy of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:214)
    at zombie.core.Core.setScreenSize(Core.java:2508)
    at zombie.GameWindow.frameStep(GameWindow.java:771)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`
just wanted to send it along. plz let me know if you need more info.
my email is (REMOVED BY DEVELOPER). thats probably the easiest way to get back with me.
i just made this gothub account to report this to you. hope this helps
Thank you!

**Comment by Angry362** [comment]
Hey MilkChocolate! Sorry for editing your message, removed the e-mail because you never know who lurks this website. On to the issue itself, it seems the lifestyle menu creation event isn't firing (could be due to a weird interaction with another mod), causing the error to appear when another event (LSMenuOnDestroy) expects it to exist but can't find it. I can't be sure of the source of the error without searching trough the whole mod list, but I just wrote a fix which will stop the error from being thrown when the event can't find the lsmenu. This fix will be in the next major update, which if all goes well should hopefully drop in a month or two. Ty for bringing this issue to me :)
