### ISSUE TITLE
Having an error with a moodle I guess

### ISSUE THREAD

**Issue by DrSweetBerry** [Angry362/Lifestyle-Mod-Project-Zomboid-#2]
My first time reporting incompatibilities with other mods or errors in general, tell me if you need more info or if this ain't the "code" you're looking for😅

function: getXYPosition -- file: LSMoodleManager.lua line # 593 | MOD: Lifestyle
function: render -- file: MF_ISMoodle.lua line # 218 | MOD: MoodleFramework

ERROR: General     , 1694199482499> 387,464,253> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: MoodlePriority of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1694199482499> 387,464,253> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: MoodlePriority of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
	at zombie.ui.UIElement.render(UIElement.java:1534)
	at zombie.ui.UIManager.render(UIManager.java:446)
	at zombie.gameStates.IngameState.renderFrameUI(IngameState.java:1183)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.gameStates.IngameState.renderframeui(IngameState.java:1172)
	at zombie.gameStates.IngameState.renderInternal(IngameState.java:1324)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.gameStates.IngameState.render(IngameState.java:1271)
	at zombie.gameStates.GameStateMachine.render(GameStateMachine.java:37)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.GameWindow.renderInternal(GameWindow.java:340)
	at zombie.GameWindow.frameStep(GameWindow.java:774)
	at zombie.GameWindow.run_ez(GameWindow.java:681)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1694199482501> 387,464,255> -----------------------------------------
STACK TRACE
-----------------------------------------
function: getXYPosition -- file: LSMoodleManager.lua line # 593 | MOD: Lifestyle
function: render -- file: MF_ISMoodle.lua line # 218 | MOD: MoodleFramework

**Comment by Angry362** [comment]
It seems it can't find the sandbox option. I can't reproduce it, but if you don't mind answering a few questions

When the issue occurred:
Did you have the mod enabled in the menu screen?
Did you have moodle framework enabled in the menu screen?

Also, can you please check if you can see the new sandbox options? Can you confirm the issue persists in a new game?

**Comment by DrSweetBerry** [comment]
> It seems it can't find the sandbox option. I can't reproduce it, but if you don't mind answering a few questions
> 
> When the issue occurred: Did you have the mod enabled in the menu screen? Did you have moodle framework enabled in the menu screen?
> 
> Also, can you please check if you can see the new sandbox options? Can you confirm the issue persists in a new game?

Sorry for not answering quickly! I was busy.

Yes, I have it enabled. (in both menu and coop server)
Yes, I have moodle framework enabled! (in both menu and coop server)

And.. no, I can't see the mod settings in sandbox.
And lastly, the error of the moodle is "fixed", but other two appeared when creating a new server. When you open the contextual menu by right-clicking on the floor (not in the inventory), it shows one error per click and when you try to play any instruments the player can't hear anything.

This is what"ErrorMagnifier" mod gave me


`attempted index: Expressions of non-table: null
function: Add -- file: AdminTestCM.lua line # 45 | MOD: Lifestyle
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@891db72b
function: createMenu -- file: ISWorldObjectContextMenu.lua line # 1543 | Vanilla
function: createMenu -- file: HeaterISWorldObjectContextMenu.lua line # 40 | MOD: Sapphire's Heaters
function: createMenu -- file: Restrain_ContextMenu.lua line # 26 | MOD: Prisonner
function: createMenu -- file: ISMenuContextWorld.lua line # 50 | Vanilla
function: createWorldMenu -- file: ISContextManager.lua line # 28 | Vanilla
function: doRClick -- file: ISObjectClickHandler.lua line # 60 | Vanilla
function: onObjectRightMouseButtonUp -- file: ISObjectClickHandler.lua line # 379 | Vanilla
java.lang.RuntimeException: attempted index: Expressions of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:214)
    at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:228)
    at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:3086)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
    at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
    at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:79)
    at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
    at zombie.ui.UIManager.update(UIManager.java:938)
    at zombie.GameWindow.logic(GameWindow.java:262)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`




`attempted index: Expressions of non-table: null
function: Add -- file: AdminTestCM.lua line # 45 | MOD: Lifestyle
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@891db72b
function: createMenu -- file: ISWorldObjectContextMenu.lua line # 1543 | Vanilla
function: createMenu -- file: HeaterISWorldObjectContextMenu.lua line # 40 | MOD: Sapphire's Heaters
function: createMenu -- file: Restrain_ContextMenu.lua line # 26 | MOD: Prisonner
function: createMenu -- file: ISMenuContextWorld.lua line # 50 | Vanilla
function: createWorldMenu -- file: ISContextManager.lua line # 28 | Vanilla
function: doRClick -- file: ISObjectClickHandler.lua line # 60 | Vanilla
function: onObjectRightMouseButtonUp -- file: ISObjectClickHandler.lua line # 379 | Vanilla
java.lang.RuntimeException: attempted index: Expressions of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:214)
    at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:228)
    at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:3086)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
    at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
    at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:79)
    at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
    at zombie.ui.UIManager.update(UIManager.java:938)
    at zombie.GameWindow.logic(GameWindow.java:262)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`


`attempted index: StrengthMultiplier of non-table: null
function: adjustStats -- file: PlayInstrumentActionWorld.lua line # 37 | MOD: Lifestyle
function: update -- file: PlayInstrumentActionWorld.lua line # 298 | MOD: Lifestyle
java.lang.RuntimeException: attempted index: StrengthMultiplier of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
    at zombie.characters.CharacterTimedActions.LuaTimedActionNew.update(LuaTimedActionNew.java:70)
    at zombie.characters.IsoGameCharacter.updateInternal(IsoGameCharacter.java:9719)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoGameCharacter.update(IsoGameCharacter.java:9464)
    at zombie.characters.IsoPlayer.updateInternal1(IsoPlayer.java:1943)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoPlayer.update(IsoPlayer.java:1924)
    at zombie.MovingObjectUpdateSchedulerUpdateBucket.update(MovingObjectUpdateSchedulerUpdateBucket.java:79)
    at zombie.MovingObjectUpdateScheduler.update(MovingObjectUpdateScheduler.java:145)
    at zombie.iso.IsoCell.ProcessObjects(IsoCell.java:2955)
    at zombie.iso.IsoCell.updateInternal(IsoCell.java:5750)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoCell.update(IsoCell.java:5696)
    at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3499)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoWorld.update(IsoWorld.java:3427)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1617)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`


I hope that helps.

**Comment by Angry362** [comment]
Thank you. It seems the source of both errors is the game not being able to find the sandbox options. Not having sandbox options showing despite having the mod enabled confirms this.

Can you open the folder media inside the lifestyle mod folder and verify if the file sandbox-option.txt is there?

One possibility is that a reupload or modpack is overwriting the main mod (they can overwrite even if not enabled, as PZ loads all mods in the mod folder when booting up the game)

**Comment by Angry362** [comment]
Update:
User with a similar issue, fixed it by cleaning his mod's folder (likely had one or more reuploads/modpacks using the same mod ID as lifestyle) :
https://steamcommunity.com/sharedfiles/filedetails/?id=2997342681&tscn=1694269591

**Comment by Angry362** [comment]
Closing the issue due to a lack of response and because I assume the issue has been solved with the last patches. Please do reach out again should you need any more help! :)
